# Generated by Django 5.2.7 on 2025-10-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.CharField(choices=[('08:00', '8:00 AM - 9:00 AM'), ('09:00', '9:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM')], default='09:00', max_length=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.CharField(choices=[('08:00', '8:00 AM - 9:00 AM'), ('09:00', '9:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM')], default='08:00', max_length=5),
        ),
    ]
