# Generated by Django 5.2.7 on 2025-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_alter_reserva_hora_fin_alter_reserva_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('archivada', 'Archivada')], default='confirmada', max_length=20),
        ),
    ]
