# Generated by Django 5.2.7 on 2025-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_cancha_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='precio_por_hora',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='Precio por Hora (COP)'),
        ),
    ]
